name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [main] # branch to trigger deployment
    paths:
      - .github/workflows/gh-pages.yaml
      - docs/**

jobs:
  pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - id: deployment
        uses: sphinx-notes/pages@v3
